**About Book Crossing Dataset**<br>

This dataset has been compiled by Cai-Nicolas Ziegler in 2004, and it comprises of three tables for users, books and ratings. Explicit ratings are expressed on a scale from 1-10 (higher values denoting higher appreciation) and implicit rating is expressed by 0.

Reference: http://www2.informatik.uni-freiburg.de/~cziegler/BX/ 

**Objective**

This project entails building a Book Recommender System for users based on user-based and item-based collaborative filtering approaches.

#### Execute the below cell to load the datasets

In [1]:
#importing necessary packages
import numpy as np
import pandas as pd

In [2]:
#Loading data
books = pd.read_csv("books.csv", sep=";", error_bad_lines=False, encoding="latin-1")
books.columns = ['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher', 'imageUrlS', 'imageUrlM', 'imageUrlL']

users = pd.read_csv('users.csv', sep=';', error_bad_lines=False, encoding="latin-1")
users.columns = ['userID', 'Location', 'Age']

ratings = pd.read_csv('ratings.csv', sep=';', error_bad_lines=False, encoding="latin-1")
ratings.columns = ['userID', 'ISBN', 'bookRating']

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.p

### Check no.of records and features given in each dataset

In [3]:
print("DataFrame : books - No. of records : {}, No. of Features : {}.".format(books.shape[0],books.shape[1]))
print("DataFrame : users - No. of records : {}, No. of Features : {}.".format(users.shape[0],users.shape[1]))
print("DataFrame : ratings - No. of records : {}, No. of Features : {}".format(ratings.shape[0],ratings.shape[1]))

DataFrame : books - No. of records : 271360, No. of Features : 8.
DataFrame : users - No. of records : 278858, No. of Features : 3.
DataFrame : ratings - No. of records : 1149780, No. of Features : 3


## Exploring books dataset

In [4]:
books.head()

ISBN                                          bookTitle  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

             bookAuthor yearOfPublication                   publisher  \
0    Mark P. O. Morford              2002     Oxford University Press   
1  Richard Bruce Wright              2001       HarperFlamingo Canada   
2          Carlo D'Este              1991             HarperPerennial   
3      Gina Bari Kolata              1999        Farrar Straus Giroux   
4       E. J. W. Barber              1999  W. W. Norton &amp; Company   

                                           imageUrlS  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                           imageUrlM  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                           imageUrlL  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

### Drop last three columns containing image URLs which will not be required for analysis

In [5]:
books.columns

Index(['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher',
       'imageUrlS', 'imageUrlM', 'imageUrlL'],
      dtype='object')

In [6]:
books.drop(['imageUrlS', 'imageUrlM', 'imageUrlL'], inplace=True, axis=1)

In [7]:
books.head()

ISBN                                          bookTitle  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

             bookAuthor yearOfPublication                   publisher  
0    Mark P. O. Morford              2002     Oxford University Press  
1  Richard Bruce Wright              2001       HarperFlamingo Canada  
2          Carlo D'Este              1991             HarperPerennial  
3      Gina Bari Kolata              1999        Farrar Straus Giroux  
4       E. J. W. Barber              1999  W. W. Norton &amp; Company

**yearOfPublication**

### Check unique values of yearOfPublication


In [8]:
books['yearOfPublication'].unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980'

As it can be seen from above that there are some incorrect entries in this field. It looks like Publisher names 'DK Publishing Inc' and 'Gallimard' have been incorrectly loaded as yearOfPublication in dataset due to some errors in csv file.


Also some of the entries are strings and same years have been entered as numbers in some places. We will try to fix these things in the coming questions.

### Check the rows having 'DK Publishing Inc' as yearOfPublication

In [9]:
books[books['yearOfPublication'] == 'DK Publishing Inc']

ISBN                                          bookTitle  \
209538  078946697X  DK Readers: Creating the X-Men, How It All Beg...   
221678  0789466953  DK Readers: Creating the X-Men, How Comic Book...   

       bookAuthor  yearOfPublication  \
209538       2000  DK Publishing Inc   
221678       2000  DK Publishing Inc   

                                                publisher  
209538  http://images.amazon.com/images/P/078946697X.0...  
221678  http://images.amazon.com/images/P/0789466953.0...

### Drop the rows having `'DK Publishing Inc'` and `'Gallimard'` as `yearOfPublication`

In [10]:
books.drop([209538, 221678], inplace=True)

In [11]:
errorlist = books[books['yearOfPublication'] == 'Gallimard'].index.to_list()

In [12]:
books.drop(errorlist, inplace=True)

In [13]:
books[(books['yearOfPublication'] == 'DK Publishing Inc') | (books['yearOfPublication'] == 'Gallimard')]

Empty DataFrame
Columns: [ISBN, bookTitle, bookAuthor, yearOfPublication, publisher]
Index: []

- We have removed records that had `'DK Publishing Inc'` and `'Gallimard'` in the yearOfPublication column. 

### Change the datatype of yearOfPublication to 'int'

In [14]:
books['yearOfPublication'] =  books['yearOfPublication'].astype('int64')

In [15]:
books.dtypes

ISBN                 object
bookTitle            object
bookAuthor           object
yearOfPublication     int64
publisher            object
dtype: object

### Drop NaNs in `'publisher'` column


In [16]:
books['publisher'].isnull().sum()

2

In [17]:
books.dropna(subset=['publisher'],inplace=True)

## Exploring Users dataset

In [18]:
print(users.shape)
users.head()

(278858, 3)


userID                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

### Get all unique values in ascending order for column `Age`

In [19]:
users['Age'].sort_values(ascending=True).unique()

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 113., 114., 115., 116., 118., 119., 123., 124., 127.,
       128., 132., 133., 136., 137., 138., 140., 141., 143., 146., 147.,
       148., 151., 152., 156., 157., 159., 162., 168., 172., 175., 183.,
       186., 189., 199., 200., 201., 204., 207., 20

Age column has some invalid entries like nan, 0 and very high values like 100 and above

### Values below 5 and above 90 do not make much sense for our book rating case...hence replace these by NaNs

In [20]:
users['Age'].fillna(0, inplace=True)

In [21]:
users['Age'].isna().sum()

0

In [22]:
users['Age'] = users['Age'].astype('int64')

In [23]:
users['Age'] = users['Age'].apply(lambda x: np.nan if x < 6 or x > 90 else x )

In [24]:
users['Age'].unique()

array([nan, 18., 17., 61., 26., 14., 25., 19., 46., 55., 32., 24., 20.,
       34., 23., 51., 31., 21., 44., 30., 57., 43., 37., 41., 54., 42.,
       50., 39., 53., 47., 36., 28., 35., 13., 58., 49., 38., 45., 62.,
       63., 27., 33., 29., 66., 40., 15., 60., 79., 22., 16., 65., 59.,
       48., 72., 56., 67., 80., 52., 69., 71., 73., 78.,  9., 64., 12.,
       74., 75., 76., 83., 68., 11., 77., 70.,  8.,  7., 81., 10.,  6.,
       84., 82., 90., 85., 86., 87., 89., 88.])

### Replace null values in column `Age` with mean

In [25]:
meanAge = round(users['Age'].mean())
meanAge

35

In [26]:
users['Age'].fillna(meanAge, inplace=True)

In [27]:
#Checking of the Age column has nan values
users['Age'].unique()

array([35., 18., 17., 61., 26., 14., 25., 19., 46., 55., 32., 24., 20.,
       34., 23., 51., 31., 21., 44., 30., 57., 43., 37., 41., 54., 42.,
       50., 39., 53., 47., 36., 28., 13., 58., 49., 38., 45., 62., 63.,
       27., 33., 29., 66., 40., 15., 60., 79., 22., 16., 65., 59., 48.,
       72., 56., 67., 80., 52., 69., 71., 73., 78.,  9., 64., 12., 74.,
       75., 76., 83., 68., 11., 77., 70.,  8.,  7., 81., 10.,  6., 84.,
       82., 90., 85., 86., 87., 89., 88.])

### Change the datatype of `Age` to `int`

In [28]:
users['Age'] = users['Age'].astype('int64')

In [29]:
print(sorted(users.Age.unique()))

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]


## Exploring the Ratings Dataset

### check the shape

In [30]:
ratings.shape

(1149780, 3)

In [31]:
n_users = users.shape[0]
n_books = books.shape[0]

In [32]:
ratings.head(5)

userID        ISBN  bookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

### Ratings dataset should have books only which exist in our books dataset. Drop the remaining rows

In [33]:
ratings = ratings[ratings.ISBN.isin(books.ISBN)]

In [34]:
ratings['userID'].count()

1031130

### Ratings dataset should have ratings from users which exist in users dataset. Drop the remaining rows

In [35]:
ratings = ratings[ratings.userID.isin(users.userID)]

In [36]:
ratings.shape

(1031130, 3)

### Consider only ratings from 1-10 and leave 0s in column `bookRating`

In [37]:
ratings['bookRating'].unique()

array([ 0,  5,  3,  6,  7,  9,  8, 10,  1,  4,  2], dtype=int64)

In [38]:
ratings_real = ratings[ratings['bookRating'] != 0 ]

In [39]:
ratings_real['bookRating'].unique()

array([ 5,  3,  6,  7,  9,  8, 10,  1,  4,  2], dtype=int64)

### Find out which rating has been given highest number of times

In [40]:
ratings_real.groupby(['bookRating'])['bookRating'].count().sort_values(ascending=False)

bookRating
8     91804
10    71225
7     66401
9     60776
5     45355
6     31687
4      7617
3      5118
2      2375
1      1481
Name: bookRating, dtype: int64

- The rating 8 is given highest number of time, followed by rating 10 and rating 7.

### **Collaborative Filtering Based Recommendation Systems**

### For more accurate results only consider users who have rated atleast 100 books

In [41]:
ratings_real.columns

Index(['userID', 'ISBN', 'bookRating'], dtype='object')

In [46]:
counts = ratings_real['userID'].value_counts()
ratings_100_more = ratings_real[ratings_real['userID'].isin(counts[counts >= 100].index)]

In [48]:
ratings_100_more.head(10)

userID        ISBN  bookRating
1456  277427  002542730X          10
1458  277427  003008685X           8
1461  277427  0060006641          10
1465  277427  0060542128           7
1474  277427  0061009059           9
1477  277427  0062507109           8
1483  277427  0132220598           8
1488  277427  0140283374           6
1490  277427  014039026X           8
1491  277427  0140390715           7

### Generating ratings matrix from explicit ratings


#### Note: since NaNs cannot be handled by training algorithms, replace these by 0, which indicates absence of ratings

In [51]:
rating_matrix = ratings_100_more.pivot(index='userID', columns='ISBN', values='bookRating').fillna(0)
rating_matrix.head()

ISBN    0000913154  0001046438  000104687X  0001047213  0001047973  \
userID                                                               
2033           0.0         0.0         0.0         0.0         0.0   
2110           0.0         0.0         0.0         0.0         0.0   
2276           0.0         0.0         0.0         0.0         0.0   
4017           0.0         0.0         0.0         0.0         0.0   
4385           0.0         0.0         0.0         0.0         0.0   

ISBN    000104799X  0001048082  0001053736  0001053744  0001055607  ...  \
userID                                                              ...   
2033           0.0         0.0         0.0         0.0         0.0  ...   
2110           0.0         0.0         0.0         0.0         0.0  ...   
2276           0.0         0.0         0.0         0.0         0.0  ...   
4017           0.0         0.0         0.0         0.0         0.0  ...   
4385           0.0         0.0         0.0         0.0         0.0  ...   

ISBN    B000092Q0A  B00009EF82  B00009NDAN  B0000DYXID  B0000T6KHI  \
userID                                                               
2033           0.0         0.0         0.0         0.0         0.0   
2110           0.0         0.0         0.0         0.0         0.0   
2276           0.0         0.0         0.0         0.0         0.0   
4017           0.0         0.0         0.0         0.0         0.0   
4385           0.0         0.0         0.0         0.0         0.0   

ISBN    B0000VZEJQ  B0000X8HIE  B00013AX9E  B0001I1KOG  B000234N3A  
userID                                                              
2033           0.0         0.0         0.0         0.0         0.0  
2110           0.0         0.0         0.0         0.0         0.0  
2276           0.0         0.0         0.0         0.0         0.0  
4017           0.0         0.0         0.0         0.0         0.0  
4385           0.0         0.0         0.0         0.0         0.0  

[5 rows x 66572 columns]

### Generate the predicted ratings using SVD function from surprise library

In [52]:
# inporting necessary libraries
from surprise import Reader
from surprise import Dataset
from surprise import accuracy
from surprise import SVD
from surprise.model_selection import train_test_split

In [53]:
reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(ratings_100_more, reader)

In [54]:
trainset = data.build_full_trainset()

In [55]:
model = SVD()
model.fit(trainset)

In [56]:
testset = trainset.build_anti_testset()

In [57]:
test_pred = model.test(testset)
test_pred[0]

Prediction(uid=277427, iid='0006542808', r_ui=7.825397747629976, est=8.401985447050063, details={'was_impossible': False})

In [58]:
accuracy.rmse(test_pred)

RMSE: 0.9908


0.9907661170895973

## Take a particular user_id

### Lets find the recommendations for user with id `2110`

#### Note: Execute the below cells to get the variables loaded

In [60]:
userID = 2110

In [61]:
user_id = 2 #2nd row in ratings matrix and predicted matrix

### Get the predicted ratings for userID `2110` and sort them in descending order

In [62]:
from collections import defaultdict

In [63]:
top_n = defaultdict(list)

def is_empty(any_structure):
    if any_structure:
        return False
    else:
        return True

def get_all_users_ratings(predictions):
    # First map the predictions to each user.
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings

    return top_n

def get_users_ratings(predictions, userID):
    if(is_empty(top_n)):
        get_all_users_ratings(predictions)
        user_ratings = top_n.get(userID)
    else:
        user_ratings = top_n.get(userID)
        
    return user_ratings

In [64]:
user_ratings = get_users_ratings(test_pred, userID)

In [65]:
user_ratings

[('0451169530', 10),
 ('0380018179', 9.832549435923353),
 ('0679723161', 9.719669504222942),
 ('0446310786', 9.654743659884648),
 ('0446365386', 9.632479463710126),
 ('015668568X', 9.59231345082882),
 ('0618002235', 9.561888246918295),
 ('0439136350', 9.548775864597928),
 ('0380813815', 9.533450178214187),
 ('006092988X', 9.53045044283351),
 ('0345361792', 9.53044988581224),
 ('0060256656', 9.513663030238147),
 ('0439139597', 9.495166838486984),
 ('0441172717', 9.487880906896265),
 ('0064400557', 9.460603301116066),
 ('0811801802', 9.41748617032945),
 ('0374199698', 9.397678015887507),
 ('0380005239', 9.396314978975662),
 ('0836218051', 9.384784002196184),
 ('0553258524', 9.370185982870593),
 ('0679417648', 9.357647716781932),
 ('0140143505', 9.350783054553572),
 ('0028604199', 9.350363106246476),
 ('0425141233', 9.341649950461775),
 ('0515119784', 9.325881289538696),
 ('0451524934', 9.323478667613202),
 ('155584376X', 9.320599390070178),
 ('0440404908', 9.319465324575868),
 ('08423291

### Create a dataframe with name `user_data` containing userID `2110` explicitly interacted books

In [66]:
user_data = ratings_real[ratings_real['userID']==2110]

In [67]:
user_data.head()

userID        ISBN  bookRating
14448    2110  0060987529           7
14449    2110  0064472779           8
14450    2110  0140022651          10
14452    2110  0142302163           8
14453    2110  0151008116           5

In [68]:
user_data.shape

(103, 3)

### Combine the user_data and and corresponding book data(`book_data`) in a single dataframe with name `user_full_info`

In [69]:
book_data = books[books['ISBN'].isin(user_data['ISBN'])]

In [70]:
book_data.shape

(103, 5)

In [71]:
book_data.head()

ISBN                                          bookTitle  \
246   0151008116                                         Life of Pi   
904   015216250X  So You Want to Be a Wizard: The First Book in ...   
1000  0064472779                                  All-American Girl   
1302  0345307674                     Return of the Jedi (Star Wars)   
1472  0671527215                  Hitchhikers's Guide to the Galaxy   

         bookAuthor  yearOfPublication           publisher  
246     Yann Martel               2002            Harcourt  
904     Diane Duane               2001  Magic Carpet Books  
1000      Meg Cabot               2003        HarperTrophy  
1302     James Kahn               1983       Del Rey Books  
1472  Douglas Adams               1984              Pocket

In [72]:
user_full_info = pd.merge(user_data, book_data, on='ISBN')

In [73]:
user_full_info.head()

userID        ISBN  bookRating  \
0    2110  0060987529           7   
1    2110  0064472779           8   
2    2110  0140022651          10   
3    2110  0142302163           8   
4    2110  0151008116           5   

                                     bookTitle       bookAuthor  \
0  Confessions of an Ugly Stepsister : A Novel  Gregory Maguire   
1                            All-American Girl        Meg Cabot   
2           Journey to the Center of the Earth      Jules Verne   
3                             The Ghost Sitter  Peni R. Griffin   
4                                   Life of Pi      Yann Martel   

   yearOfPublication      publisher  
0               2000    Regan Books  
1               2003   HarperTrophy  
2               1965  Penguin Books  
3               2002   Puffin Books  
4               2002       Harcourt

### Get top 10 recommendations for above given userID from the books not already rated by that user

In [74]:
not_rated_books = ratings[(ratings['userID']==2110) & (ratings['bookRating']==0)]['ISBN'].tolist()

In [75]:
def get_user_rating_books_list(user_ratings):
    books_list = []
    for isbn, user_rating in user_ratings:
        if(isbn in not_rated_books):
            #print(isbn, user_rating)
            books_list.append(isbn)
    return books_list

def get_top_k_books_list(books_list, k):
    return books_list[:k]

In [76]:
user_books_list = get_user_rating_books_list(user_ratings)
top_10_recommondations = get_top_k_books_list(user_books_list, 10)
print('Top 10 recommendations for userid : '+str(userID))
for item in top_10_recommondations:
    print('ISBN ID : {}'.format(str(item)))

Top 10 recommendations for userid : 2110
ISBN ID : 0140298479
ISBN ID : 0440901588
ISBN ID : 0515133973
ISBN ID : 0671740881
ISBN ID : 0670820555
ISBN ID : 0439164567
ISBN ID : 0590010891
ISBN ID : 0886774829
ISBN ID : 0451149513
ISBN ID : 0671517643


In [77]:
books[books['ISBN'].isin(top_10_recommondations)]

ISBN                                          bookTitle  \
2488   0140298479                  Bridget Jones: The Edge of Reason   
2659   0671740881  EVIL ONE (PHANTOM VALLEY 1) : EVIL ONE (Phanto...   
2685   0439164567                         Shipwreck (Island, Book 1)   
4287   0670820555  Spy Catcher: The Candid Autobiography of a Sen...   
6100   0671517643                                       LITTLE WOMEN   
8468   0440901588                           A Swiftly Tilting Planet   
12151  0515133973                                     Midnight Bayou   
16225  0590010891            Star Wars Episode I: The Phantom Menace   
16244  0451149513                                                 It   
16300  0886774829                   Stronghold (Dragon Star, Book 1)   

              bookAuthor  yearOfPublication                    publisher  
2488      Helen Fielding               2001                Penguin Books  
2659          Lynn Beach               1991                      Aladdin  
2685       Gordon Korman               2001  Hyperion Books for Children  
4287        Peter Wright               1987                  Penguin USA  
6100   Louisa May Alcott               1994                       Pocket  
8468   Madeleine L'Engle               1979                   Laure Leaf  
12151       Nora Roberts               2004                   Jove Books  
16225  Patricia C. Wrede               1999                   Scholastic  
16244       Stephen King               1987             New Amer Library  
16300       Melanie Rawn               1994                    Daw Books