# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [3]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
# modules to use dataset from sklearn
from sklearn import datasets

irisDS = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [5]:
print('Listing the features in the dataset')
print('--'*20)
independendData = irisDS.data
print(independendData)

Listing the features in the dataset
----------------------------------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1

In [6]:
dependentData = irisDS.target
print('Listing the target Data')
print('--'*20)
print(dependentData)

Listing the target Data
----------------------------------------
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independendData, dependentData, test_size=0.25, random_state=42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [10]:
y_train = tf.keras.utils.to_categorical(
    y_train,
    num_classes=3,
    dtype='float32'
)

In [11]:
y_test = tf.keras.utils.to_categorical(
    y_test,
    num_classes=3,
    dtype='float32'
)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [12]:
model = tf.keras.Sequential()

## Question 6


### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [13]:
from tensorflow.keras import layers
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(3, activation='softmax')
])

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [14]:
from tensorflow.keras.optimizers import SGD
opt = SGD(learning_rate=0.1)

In [15]:
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 33        
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [17]:
model.fit(X_train, y_train, epochs=100)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 2s 13ms/sample - loss: 1.2820 - accuracy: 0.4643
Epoch 2/100
112/112 [==============================] - 0s 275us/sample - loss: 0.8234 - accuracy: 0.5625
Epoch 3/100
112/112 [==============================] - 0s 266us/sample - loss: 0.5888 - accuracy: 0.6518
Epoch 4/100
112/112 [==============================] - 0s 171us/sample - loss: 0.6862 - accuracy: 0.6429
Epoch 5/100
112/112 [==============================] - 0s 159us/sample - loss: 0.4917 - accuracy: 0.7768
Epoch 6/100
112/112 [==============================] - 0s 172us/sample - loss: 0.4935 - accuracy: 0.6607
Epoch 7/100
112/112 [==============================] - 0s 200us/sample - loss: 0.4463 - accuracy: 0.8482
Epoch 8/100
112/112 [==============================] - 0s 120us/sample - loss: 0.4339 - accuracy: 0.7946
Epoch 9/100
112/112 [==============================] - 0s 93us/sample - loss: 0.4777 - accuracy: 0.8393
Epoch 10/100
112/112 [==============

## Question 10

### Make predictions
- Predict labels on one row

In [18]:
model.predict(X_test[0:1])

array([[0.00165643, 0.9574754 , 0.04086812]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [19]:
model.predict_classes(X_test[0:1])

array([1], dtype=int64)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [ ]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [20]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [21]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [ ]:
import pandas as pd
df = pd.read_csv('prices.csv')

In [157]:
df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [ ]:
df.drop(columns=['date', 'symbol'], inplace = True)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [ ]:
newdf = df.iloc[0:100]

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [ ]:
newdf.columns
X = newdf.drop(columns=['volume'], axis=1)
y = newdf['volume']

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [161]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
open     100 non-null float64
close    100 non-null float64
low      100 non-null float64
high     100 non-null float64
dtypes: float64(4)
memory usage: 3.2 KB


In [ ]:
for cols in X.columns:
  X[cols] = X[cols].astype('float32')

In [163]:
y.dtype

dtype('float64')

In [ ]:
y = y.astype('float32')

In [ ]:
X = X.to_numpy()
y = y.to_numpy()

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow import math

In [ ]:
X = math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [169]:
tf.zeros([1,4])

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [ ]:
class Model(object):
  def __init__(self):
    self.W1 = tf.Variable(5.0)
    self.W2 = tf.Variable(4.0)
    self.W3 = tf.Variable(3.0)
    self.W4 = tf.Variable(2.0)
    self.b = tf.Variable(0.2)

  def __call__(self, x1, x2, x3, x4):
    return self.b + self.W1 * x1 + self.W2 * x2 + self.W3 * x3 + self.W4 * x4

model = Model()

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

### Observe values of Weight
- Print the updated values

### Observe values of Bias
- Print the updated values