## Lists, Dictionaries and Sets in Python

## Part 1

### Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [1]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]


List can also be created by using list() function. 

In [2]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


Adding to an existing list

### Question 1

Add 10 to list l1 given above.

[ **Hint: ** Use **append** ]

In [3]:
l1.append(10)    #appending value 10 to list l1

Removing from an existing list
    
### Question 2

Remove 10 from l1.

[ **Hint:** Use **remove**]

In [4]:
l1.remove(10)    # Removing value 10 from the list l1 using remove. Remove take the variable to be removed and not the index.
                 # To use index to remove a value we need to use delete().

Joining 2 lists

### Question 3

[ **Hint: ** Use **+** operator or **extend**]

In [5]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [6]:
print(l1+l2)    # + will concatinate two lists

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]


Number List

### Question 4

Find Range and Mean of l3.

l3 = [2,4,6,8]

[ **Hint: ** Use **len(),sum(), min(), max()** functions ]
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [7]:
import numpy as np            # importing numpy since we have group function to be executed
l3 = [2,4,6,8]                # defining the list 
l3 = np.array(l3)             # convert python list as ndarry for computing basic agregate functions
print(type(l3))               # Verifing if the dtype is ndarry

<class 'numpy.ndarray'>


In [8]:
print("Length of the list : {}".format(len(l3)))
print("Sum of the list l3 : {}".format(l3.sum()))
print("The min value in the list l3 : {}".format(l3.min()))
print("The max value in the list l3 : {}".format(l3.max()))

Length of the list : 4
Sum of the list l3 : 20
The min value in the list l3 : 2
The max value in the list l3 : 8


In [9]:
l3 = list(l3)
print("Length {}".format(len(l3)))
print("Sum {}".format(sum(l3)))
print("Min {}".format(min(l3)))
print("Max {}".format(max(l3)))

Length 4
Sum 20
Min 2
Max 8


Count the occurances of an element in a given list.

### Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ **Hint: ** Use ** + operator to add multiple elements in the array and count() function to print the occurences**]

In [10]:
l3 = list(l3)                       # converting the l3(ndarray) back to list to append more data
l4 = [0,1,3,3,5,5,7,9]              # defining the l4 list data that will be appended to l3
l5 = l3 + l4                        # Concating l3 and l4
print(l5.count(5))                  # printing the count for the varible 5 that is present in the list
print(l5)                           # printing the l5 list for verification

2
[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]


Sorting and Reversing a list

### Question 6
sort and print l3 in ascending and descending order sequentially (given above)

**(Hint: Use .sort() function)**

In [11]:
%config IPCompleter.greedy=True                     # adding for intellisense 
l3 = l5
print("Perfoming Ascending Sort...")    
l3.sort()                                           # sort function will sort the data in a list in acesnding order by default             
print("Printing l3 in ascending order")
print(l3)

Perfoming Ascending Sort...
Printing l3 in ascending order
[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]


In [12]:
print("Perfoming Descending Sort...")
l3.sort(reverse=True)                               # will we add the reverse=True parameter to sort the sorting done will be 
print("Printing l3 in descending order")            # in descending order.
print(l3)

Perfoming Descending Sort...
Printing l3 in descending order
[9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]


### Functions

**Example:**

**def** function_name(args)**:**
    
    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [13]:
#method 1:
def sum_3(a, b,c):
    return(a+b+c)

In [14]:
#method 3:
def sum_3_args(*args):
    a = 0
    for item in args:
        a = a + item
    return a

In [15]:
print("The sum of three number with definite defined paraters in defined function is {}".format(sum_3(1,1,1)))
print("The sum of three numbers with *args as parameter to defined function is {}".format(sum_3_args(2,2,2)))

The sum of three number with definite defined paraters in defined function is 3
The sum of three numbers with *args as parameter to defined function is 6


### Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

In [16]:
f = lambda x,y,z : x+y+z
f(2,3,4)

9

# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [17]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [18]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [19]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [20]:
idmat = np.identity(5)
idmat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [21]:
#using np.matrix
matrix = np.matrix([9,8,7,6,5,4,3,2,1])
matrix = matrix.reshape(3,3)             #changing the shape of the matrix to 3*3 from 9*1 
print(matrix.shape)
print(matrix)

(3, 3)
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [22]:
# without using np.matrix
mat2d = np.array([9,8,7,6,5,4,3,2,1])
mat2d = mat2d.reshape(3,3)
print(mat2d.shape)
print(mat2d)

(3, 3)
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [23]:
mat2sTranspose = mat2d.T
print(mat2sTranspose)

[[9 6 3]
 [8 5 2]
 [7 4 1]]


### Question 4
Add + 1 to all the elements in the given matrix.

In [24]:
mat2add= mat2sTranspose+1
mat2add

array([[10,  7,  4],
       [ 9,  6,  3],
       [ 8,  5,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

In [25]:
#Subraction to the matrix
mat2sub = mat2sTranspose - 2
mat2sub

array([[ 7,  4,  1],
       [ 6,  3,  0],
       [ 5,  2, -1]])

In [26]:
# multiplication on the matrix
mat2mul = mat2sTranspose * 3
mat2mul

array([[27, 18,  9],
       [24, 15,  6],
       [21, 12,  3]])

In [27]:
# Division on the matirx
mat2div = mat2sTranspose / 3
mat2div

array([[3.        , 2.        , 1.        ],
       [2.66666667, 1.66666667, 0.66666667],
       [2.33333333, 1.33333333, 0.33333333]])

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [28]:
nd6 = np.array([[ 1, 4, 9, 121, 144, 169], [ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])

In [29]:
nd6.mean()

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [30]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[7,8,9],[1,2,3],[4,5,6]])
dotprod = np.dot(arr1,arr2)
print(dotprod)                 # printing the dot product matrix

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# Pandas

We have seen Numpy in the last section. It is good at performing math operation on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](http://pandas.pydata.org/pandas-docs/version/0.23/dsintro.html)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [31]:
import numpy as np
import pandas as pd

In [32]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

[**Hint:** Use **.Series**]

In [33]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [34]:
series = pd.Series(d1)
print(series)

a    1
b    2
c    3
dtype: int64


You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


[ **Hint: ** Use **np.dot()** ]

In [35]:
seriesdotprod = np.dot(series, series1)
print(seriesdotprod)                     # printing the dotproduct for series and series1

14


## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [36]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.



In [37]:
#Selecting the second row can be done by many ways few are done below
df1[1:2]

a  b  c
1  2  4  7

In [38]:
df1.iloc[1:2]

a  b  c
1  2  4  7

### Question 4

Select column c in second row of df1.

[ **Hint: ** For using labels use **df.loc[row, column]**. For using numeric indexed use **df.iloc[]**. For using mixture of numeric indexes and labels use **df.ix[row, column]** ]



In [39]:
# accessing columns in multiple formats
df1['c']

0    6
1    7
2    8
Name: c, dtype: int64

In [40]:
df1.loc[:,'c']

0    6
1    7
2    8
Name: c, dtype: int64

In [41]:
df1.iloc[:,-1]

0    6
1    7
2    8
Name: c, dtype: int64

In [42]:
df1.iloc[:,2]

0    6
1    7
2    8
Name: c, dtype: int64

## Using Dataframes on a dataset

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors 

In [43]:
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']


Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


[ **Hint: ** Use **type()** and **df.shape** ]

In [44]:
mtcars.shape

(32, 12)

### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

[**Hint:** Use **.head()** and **.tail()**]

In [45]:
# .head function returns the first 5 records from the dataset, providing 10 as an argument it will return first 10 records.
mtcars.head(10)

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   
Valiant                      Valiant  18.1    6  225.0  105  2.76  3.460   
Duster 360                Duster 360  14.3    8  360.0  245  3.21  3.570   
Merc 240D                  Merc 240D  24.4    4  146.7   62  3.69  3.190   
Merc 230                    Merc 230  22.8    4  140.8   95  3.92  3.150   
Merc 280                    Merc 280  19.2    6  167.6  123  3.92  3.440   

                    qsec  vs  am  gear  carb  
name                                          
Mazda RX4          16.46   0   1     4     4  
Mazda RX4 Wag      17.02   0   1     4     4  
Datsun 710         18.61   1   1     4     1  
Hornet 4 Drive     19.44   1   0     3     1  
Hornet Sportabout  17.02   0   0     3     2  
Valiant            20.22   1   0     3     1  
Duster 360         15.84   0   0     3     4  
Merc 240D          20.00   1   0     4     2  
Merc 230           22.90   1   0     4     2  
Merc 280           18.30   1   0     4     4

In [46]:
# .tail function returns the last 5 rows in the dataset by default, providing 10 as a argument returns 10 records.
mtcars.tail(10)

name   mpg  cyl   disp   hp  drat     wt   qsec  \
name                                                                            
AMC Javelin            AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   
Camaro Z28              Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   
Pontiac Firebird  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   
Fiat X1-9                Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   
Porsche 914-2        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   
Lotus Europa          Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   
Ford Pantera L      Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   
Ferrari Dino          Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   
Maserati Bora        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   
Volvo 142E              Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   

                  vs  am  gear  carb  
name                                  
AMC Javelin        0   0     3     2  
Camaro Z28         0   0     3     4  
Pontiac Firebird   0   0     3     2  
Fiat X1-9          1   1     4     1  
Porsche 914-2      0   1     5     2  
Lotus Europa       1   1     5     2  
Ford Pantera L     0   1     5     4  
Ferrari Dino       0   1     5     6  
Maserati Bora      0   1     5     8  
Volvo 142E         1   1     4     2

### Question 7

Print all the column labels in the given dataset - mtcars.

[ **Hint: ** Use **df.columns** ]

In [47]:
# columns can be accessed using the function .columns
mtcars.columns

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

**Hint: **  
mtcars.ix[:,:] gives all rows and columns in the dataset.

In [48]:
mtcars.iloc[:6,0:3]

name   mpg  cyl
name                                           
Mazda RX4                  Mazda RX4  21.0    6
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6
Datsun 710                Datsun 710  22.8    4
Hornet 4 Drive        Hornet 4 Drive  21.4    6
Hornet Sportabout  Hornet Sportabout  18.7    8
Valiant                      Valiant  18.1    6

In [49]:
mtcars[['name','mpg','cyl']].head(6) #another way to select the first 6 rows using head function and using key as a parameter for the colums. This is a unconventional method of accessing

name   mpg  cyl
name                                           
Mazda RX4                  Mazda RX4  21.0    6
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6
Datsun 710                Datsun 710  22.8    4
Hornet 4 Drive        Hornet 4 Drive  21.4    6
Hornet Sportabout  Hornet Sportabout  18.7    8
Valiant                      Valiant  18.1    6